#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# ContaNeta — 1-Click Bootstrap for Ubuntu 22.04+ VPS
#
# Idempotent: safe to re-run. Creates user, installs deps,
# sets up dirs, venv, systemd, logrotate, Caddy, firewall.
#
# Usage:
#   sudo bash deploy/bootstrap_ubuntu.sh
#
# Customize with env vars:
#   APP_DIR=/opt/contaneta DATA_DIR=/var/lib/contaneta sudo bash deploy/bootstrap_ubuntu.sh
# ──────────────────────────────────────────────────────────────
set -euo pipefail

APP_USER="${APP_USER:-contaneta}"
APP_DIR="${APP_DIR:-/opt/contaneta}"
DATA_DIR="${DATA_DIR:-/var/lib/contaneta}"
LOG_DIR="${LOG_DIR:-/var/log/contaneta}"
BACKUP_DIR="${BACKUP_DIR:-/var/backups/contaneta}"

echo "═══════════════════════════════════════════════"
echo "  ContaNeta Production Bootstrap"
echo "═══════════════════════════════════════════════"
echo "  App dir:    $APP_DIR"
echo "  Data dir:   $DATA_DIR"
echo "  Log dir:    $LOG_DIR"
echo "  Backup dir: $BACKUP_DIR"
echo "  User:       $APP_USER"
echo "═══════════════════════════════════════════════"
echo

# ── 1) System dependencies ────────────────────────────────────
echo "--- [1/10] System packages ---"
apt-get update -qq
apt-get install -y -qq \
    python3 python3-pip python3-venv \
    php-cli php-curl php-xml php-mbstring php-sqlite3 \
    sqlite3 unzip git curl ufw logrotate

# ── 2) Install Caddy ──────────────────────────────────────────
echo "--- [2/10] Caddy web server ---"
if ! command -v caddy &>/dev/null; then
    apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
        | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg 2>/dev/null || true
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
        | tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
    apt-get update -qq
    apt-get install -y -qq caddy
    echo "  Caddy installed"
else
    echo "  Caddy already installed ($(caddy version 2>/dev/null | head -1))"
fi

# ── 3) Create app user (no root shell) ────────────────────────
echo "--- [3/10] User: $APP_USER ---"
if ! id "$APP_USER" &>/dev/null; then
    useradd -r -m -s /usr/sbin/nologin "$APP_USER"
    echo "  Created system user: $APP_USER"
else
    echo "  User $APP_USER already exists"
fi

# ── 4) Create directories ─────────────────────────────────────
echo "--- [4/10] Directories ---"
mkdir -p "$APP_DIR"
mkdir -p "$DATA_DIR/storage/xml_files"
mkdir -p "$DATA_DIR/storage/credentials"
mkdir -p "$DATA_DIR/storage/temp"
mkdir -p "$DATA_DIR/storage/uploads"
mkdir -p "$LOG_DIR"
mkdir -p "$BACKUP_DIR"

chown -R "$APP_USER:$APP_USER" "$APP_DIR"
chown -R "$APP_USER:$APP_USER" "$DATA_DIR"
chown -R "$APP_USER:$APP_USER" "$LOG_DIR"
chown -R "$APP_USER:$APP_USER" "$BACKUP_DIR"
chmod 700 "$DATA_DIR/storage/credentials"

echo "  $APP_DIR         (application code)"
echo "  $DATA_DIR        (database + storage)"
echo "  $LOG_DIR         (logs)"
echo "  $BACKUP_DIR      (backups)"

# ── 5) Clone or detect repo ───────────────────────────────────
echo "--- [5/10] Application code ---"
if [ -d "$APP_DIR/app.py" ] || [ -f "$APP_DIR/app.py" ]; then
    echo "  Code already present at $APP_DIR"
else
    echo "  ⚠  Clone your repo to $APP_DIR:"
    echo "     sudo -u $APP_USER git clone YOUR_REPO_URL $APP_DIR"
    echo "     (or scp your deploy zip and unzip it there)"
fi

# ── 6) Python virtualenv + dependencies ───────────────────────
echo "--- [6/10] Python virtualenv ---"
if [ ! -d "$APP_DIR/.venv" ]; then
    sudo -u "$APP_USER" python3 -m venv "$APP_DIR/.venv"
    echo "  Created .venv"
fi
sudo -u "$APP_USER" "$APP_DIR/.venv/bin/pip" install -q --upgrade pip 2>/dev/null || true
if [ -f "$APP_DIR/requirements.txt" ]; then
    sudo -u "$APP_USER" "$APP_DIR/.venv/bin/pip" install -q -r "$APP_DIR/requirements.txt" 2>/dev/null || true
    echo "  Dependencies installed from requirements.txt"
fi
# Ensure gunicorn + uvicorn are installed
sudo -u "$APP_USER" "$APP_DIR/.venv/bin/pip" install -q gunicorn uvicorn 2>/dev/null || true

# ── 7) .env file ──────────────────────────────────────────────
echo "--- [7/10] Environment file ---"
if [ ! -f "$DATA_DIR/.env" ]; then
    if [ -f "$APP_DIR/deploy/.env.example.prod" ]; then
        cp "$APP_DIR/deploy/.env.example.prod" "$DATA_DIR/.env"
    elif [ -f "$APP_DIR/.env.example" ]; then
        cp "$APP_DIR/.env.example" "$DATA_DIR/.env"
    else
        cat > "$DATA_DIR/.env" << ENVEOF
# ContaNeta Production — generated by bootstrap
ENV=prod
DEV_MODE=0
ALLOW_DEMO_PORTAL=0
SESSION_SECRET=$(python3 -c 'import secrets; print(secrets.token_hex(32))')
AT_REST_MASTER_KEY=$(python3 -c 'import secrets; print(secrets.token_hex(32))')
APP_DB_PATH=$DATA_DIR/invoicing.db
APP_STORAGE_PATH=$DATA_DIR/storage
BACKUP_DIR=$BACKUP_DIR
LOG_FILE=$LOG_DIR/app.log
COOKIE_SECURE=1
SITE_URL=https://YOUR_DOMAIN.com
# STRIPE_SECRET_KEY=
# STRIPE_WEBHOOK_SECRET=
# STRIPE_PRICE_ID=
# SENTRY_DSN=
# PHP_BIN=php
ENVEOF
    fi
    chown "$APP_USER:$APP_USER" "$DATA_DIR/.env"
    chmod 600 "$DATA_DIR/.env"
    echo "  Created $DATA_DIR/.env — EDIT WITH REAL VALUES"
else
    echo "  $DATA_DIR/.env already exists"
fi
# Symlink from APP_DIR for convenience
if [ ! -L "$APP_DIR/.env" ] && [ ! -f "$APP_DIR/.env" ]; then
    ln -sf "$DATA_DIR/.env" "$APP_DIR/.env"
    echo "  Symlinked $APP_DIR/.env -> $DATA_DIR/.env"
fi

# ── 8) systemd services + timers ──────────────────────────────
echo "--- [8/10] systemd services ---"
for svc in contaneta-web contaneta-sat-worker contaneta-sat-scheduler contaneta-backup; do
    src="$APP_DIR/deploy/systemd/${svc}.service"
    if [ -f "$src" ]; then
        cp "$src" /etc/systemd/system/
        echo "  Installed ${svc}.service"
    fi
done
for timer in contaneta-sat-scheduler contaneta-backup; do
    src="$APP_DIR/deploy/systemd/${timer}.timer"
    if [ -f "$src" ]; then
        cp "$src" /etc/systemd/system/
        echo "  Installed ${timer}.timer"
    fi
done
systemctl daemon-reload

# ── 9) Logrotate ──────────────────────────────────────────────
echo "--- [9/10] Logrotate ---"
cat > /etc/logrotate.d/contaneta << 'LOGROTATE'
/var/log/contaneta/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    copytruncate
    su contaneta contaneta
}
LOGROTATE
echo "  Installed /etc/logrotate.d/contaneta"

# ── 10) Firewall ──────────────────────────────────────────────
echo "--- [10/10] Firewall ---"
ufw allow 22/tcp   >/dev/null 2>&1 || true
ufw allow 80/tcp   >/dev/null 2>&1 || true
ufw allow 443/tcp  >/dev/null 2>&1 || true
echo "  Allowed ports: 22 (SSH), 80 (HTTP), 443 (HTTPS)"
echo "  Enable with: sudo ufw --force enable"

# ── Done ──────────────────────────────────────────────────────
echo
echo "═══════════════════════════════════════════════"
echo "  Bootstrap complete!"
echo "═══════════════════════════════════════════════"
echo
echo "Next steps:"
echo
echo "  1) Edit .env with real values:"
echo "     sudo -u $APP_USER nano $DATA_DIR/.env"
echo
echo "  2) Set up Caddy (HTTPS):"
echo "     sudo cp $APP_DIR/deploy/caddy/Caddyfile /etc/caddy/Caddyfile"
echo "     sudo sed -i 's/TU_DOMINIO.com/YOUR_DOMAIN.com/g' /etc/caddy/Caddyfile"
echo "     sudo systemctl enable --now caddy"
echo
echo "  3) Start services:"
echo "     sudo systemctl enable --now contaneta-web"
echo "     sudo systemctl enable --now contaneta-sat-worker"
echo "     sudo systemctl enable --now contaneta-sat-scheduler.timer"
echo "     sudo systemctl enable --now contaneta-backup.timer"
echo
echo "  4) Verify:"
echo "     curl http://localhost:8000/health"
echo "     curl https://YOUR_DOMAIN.com/health"
echo
echo "  5) Smoke test:"
echo "     BASE_URL=https://YOUR_DOMAIN.com bash $APP_DIR/scripts/smoke_prod.sh"
echo
