"""Constants for bank statement PDF parsing: date patterns, month names, bank keywords, stopwords."""
import re

_DATE_PATTERNS = [
    re.compile(r"^(?P<d>\d{2})[\/\-](?P<m>\d{2})[\/\-](?P<y>\d{2,4})\b"),
    re.compile(r"^(?P<y>\d{4})[\/\-](?P<m>\d{2})[\/\-](?P<d>\d{2})\b"),
    re.compile(r"^(?P<d>\d{2})[\/\-\s](?P<mon>[A-Za-zÁÉÍÓÚÜÑ\.]{3,})[\/\-\s](?P<y>\d{2,4})\b"),
]

_MONTHS = {
    # ES
    "ENE": 1,
    "FEB": 2,
    "MAR": 3,
    "ABR": 4,
    "MAY": 5,
    "JUN": 6,
    "JUL": 7,
    "AGO": 8,
    "SEP": 9,
    "SET": 9,
    "OCT": 10,
    "NOV": 11,
    "DIC": 12,
    # EN
    "JAN": 1,
    "APR": 4,
    "AUG": 8,
    "DEC": 12,
}

_BANK_KEYWORDS = [
    ("BBVA", ["BBVA", "BANCOMER"]),
    ("SANTANDER", ["SANTANDER"]),
    ("BANORTE", ["BANORTE"]),
    ("CITIBANAMEX", ["CITIBANAMEX", "BANAMEX"]),
    ("HSBC", ["HSBC"]),
    ("SCOTIABANK", ["SCOTIABANK", "SCOTIA"]),
    ("INBURSA", ["INBURSA"]),
    ("AZTECA", ["BANCO AZTECA", "AZTECA"]),
]

_STOPWORDS_CP = {
    "PAGO",
    "PAGOS",
    "COMPRA",
    "COMPRAS",
    "CARGO",
    "ABONO",
    "DEPOSITO",
    "DEPÓSITO",
    "DEP",
    "TRANSFERENCIA",
    "TRANSFER",
    "TRANSF",
    "TRASPASO",
    "TRASP",
    "SPEI",
    "SPID",
    "COMISION",
    "COMISIONES",
    "IVA",
    "REF",
    "REFERENCIA",
    "FOLIO",
    "AUT",
    "AUTORIZACION",
    "AUTORIZACIÓN",
    "ID",
    "NUM",
    "NO",
    "CTA",
    "CUENTA",
    "TARJ",
    "TARJETA",
    "DEBITO",
    "DÉBITO",
    "CREDITO",
    "CRÉDITO",
    "POS",
    "TPV",
}

_KNOWN_COUNTERPARTIES = [
    "AMAZON",
    "UBER",
    "DIDI",
    "CFE",
    "TELCEL",
    "TELMEX",
    "AT&T",
    "MOVISTAR",
    "TOTALPLAY",
    "IZZI",
    "NETFLIX",
    "SPOTIFY",
    "GOOGLE",
    "APPLE",
    "MICROSOFT",
    "AWS",
    "OPENAI",
    "ADOBE",
    "WALMART",
    "COSTCO",
    "SORIANA",
    "OXXO",
    "7-ELEVEN",
    "SEVEN",
    "PEMEX",
]
